<a href="https://colab.research.google.com/github/harry9879/Layers-weights-and-bias/blob/main/Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[]


In [ ]:
layer = tf.keras.layers.Dense(100)
layer = tf.keras.layers.Dense(10 , input_shape = (None, 5))

In [ ]:
zeros_vector = tf.zeros([10,5])
zeros_vector
layer(zeros_vector)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
layers.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.59169585, -0.33411348,  0.15585989, -0.20072901, -0.19696653,
          0.2653485 , -0.37251735,  0.17600214, -0.48906785,  0.06055707],
        [ 0.45399934, -0.39991015,  0.17747462,  0.45701987,  0.36440295,
         -0.0989064 , -0.52279276,  0.33361888, -0.5242037 ,  0.21960568],
        [ 0.48588496,  0.00984788, -0.19590932,  0.51586336,  0.45417887,
          0.00240403,  0.02115858, -0.08771437,  0.5484615 , -0.1026215 ],
        [ 0.61277527,  0.6197135 , -0.4569243 , -0.615763  ,  0.0746364 ,
         -0.06221396, -0.5833093 , -0.41627288,  0.02981812,  0.52393466],
        [ 0.6212917 , -0.59361494,  0.30568004, -0.3815902 , -0.6263377 ,
         -0.07163161,  0.40905374, -0.24526367, -0.33680972, -0.10566789]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [ ]:
layer.kernel , layer.bias

(<tf.Variable 'dense_3/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.09885526,  0.0310241 , -0.61206114,  0.6291688 , -0.2917289 ,
          0.55285865,  0.51919025, -0.14498994, -0.04408002,  0.18525654],
        [-0.28943133, -0.46304423,  0.09527248,  0.3449549 ,  0.42776257,
          0.170986  ,  0.45476896, -0.08858138, -0.0118134 ,  0.32109386],
        [ 0.37505895,  0.13168311, -0.30739108,  0.02297801,  0.17195404,
         -0.47432777, -0.15418524,  0.26068926, -0.55801487, -0.35140988],
        [ 0.5925632 , -0.20504805,  0.16268247,  0.4483258 ,  0.5903961 ,
          0.4270864 , -0.32244918,  0.430157  , -0.35500154, -0.48114252],
        [-0.61162627, -0.366172  , -0.28461075, -0.37844744, -0.601888  ,
         -0.09101766, -0.43071714,  0.30859965, -0.31216386, -0.01269251]],
       dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [ ]:
# class MyDenseLayer(tf.keras.layers.Layer):
#   def __init__(self, num_outputs):
#     super(MyDenseLayer, self).__init__()
#     self.num_outputs = num_outputs

#   def build(self, input_shape):
#     self.kernel = self.add_weight("kernel",
#                                   shape=[int(input_shape[-1]),
#                                          self.num_outputs])
#   def call(self , inputs):
#     return tf.matmul(inputs, self.kernel)

# # layer = MyDenseLayer(10)

In [ ]:
_ = layer(tf.zeros([10,5]))

In [ ]:
print([var.name for var in layer.trainable_variables])

['my_dense_layer/kernel:0']


In [ ]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self , num_outputs):
    super(MyDenseLayer, self).__init__()
    self.num_outputs = num_outputs
  def build(self, input_shape):
    self.kernel = self.add_weight('kernel',
                                  shape=[int(input_shape[-1]),
                                                   self.num_outputs])
  def call(self, inputs):
    return tf.matmul(inputs, self.kernel)

layer = MyDenseLayer(10)

In [ ]:
_ = layer(tf.zeros([10, 5])) # Calling the layer '.builds it'

In [ ]:
print([var.name for var in layer.trainable_variables])

['my_dense_layer_2/kernel:0']


In [ ]:
class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name='')
    filters1, filters2, filters3 = filters

    self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()

    self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
    self.bn2b = tf.keras.layers.BatchNormalization()

    self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()

  def call(self, input_tensor, training=False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2b(x)
    x = self.bn2b(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2c(x)
    x = self.bn2c(x, training=training)

    x += input_tensor
    return tf.nn.relu(x)


block = ResnetIdentityBlock(1, [1, 2, 3])

In [ ]:
_ = block(tf.zeros([1,2,3,3]))

In [ ]:
block.layers

In [ ]:
len(block.variables)

18

In [ ]:
block.summary(())

Model: ""
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_27 (Conv2D)          multiple                  4         
                                                                 
 batch_normalization_26 (Bat  multiple                 4         
 chNormalization)                                                
                                                                 
 conv2d_28 (Conv2D)          multiple                  4         
                                                                 
 batch_normalization_27 (Bat  multiple                 8         
 chNormalization)                                                
                                                                 
 conv2d_29 (Conv2D)          multiple                  9         
                                                                 
 batch_normalization_28 (Bat  multiple                 12        
